#!/usr/bin/env sh
# shellcheck enable=all

if test -z "${__EXEC_DIR}"; then
  realpath=$(realpath -e "$0")
  __EXEC_DIR=$(dirname "${realpath}")
  unset -v realpath
fi

_cx_lib=$(realpath -e "${__EXEC_DIR}/source/color-echo.sh")

# shellcheck source=source/zx.lib.posix.sh
. "${_cx_lib}"

unset -v _cx_lib

_cx "${@}"
