#!/usr/bin/env sh
# shellcheck enable=all

if test -z "${__EXEC_DIR}"; then
  realpath=$(realpath -e "$0")
  __EXEC_DIR=$(dirname "${realpath}")
  unset -v realpath
fi

_zx_lib=$(realpath -e "${__EXEC_DIR}/source/zx.lib.posix.sh")

# shellcheck source=source/zx.lib.posix.sh
. "${_zx_lib}"

unset -v _zx_lib

_zx "${@}"
